import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Script 
          src="https://charbot-mobi.vercel.app/chatbot-widget.js"
          strategy="afterInteractive"
          onLoad={() => {
            const script = document.createElement("script");
            script.innerHTML = `
              window.CHAT_URL = "https://moby.host/app/hAW9B";
            `;
            document.body.appendChild(script);
          }}
        />
      </body>
    </html>
  );
}
